name: readout # read by workflow
control:
  mode: direct
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: readout
    type: push
    rateLogging: "1"
    addressing: ipc
    transport: shmem
properties: {}
command: 
  env: []
  shell: true
  arguments:
    - "file:/home/flp/readout.cfg"
  value: >-
    eval `aliswmod load Readout Control-OCCPlugin` &&
    readout.exe
