name: readout-proxy
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: "from_readout-proxy_to_Dispatcher"
    type: "push"
command:
  shell: true
  value: >-
    eval `aliswmod load QualityControl Control-OCCPlugin` &&
    o2-qc-run-readout -b | o2-qc-run-qc --config json:///etc/flp.d/qc/readout.json  | o2-qc-run-readout
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "no-op://"
    - "--id"
    - "readout-proxy"
    - "--log-color"
    - "false"
    - "--start-value-enumeration"
    - "0"
    - "--step-value-enumeration"
    - "1"

