name: stfb-qc-dispatcher
defaults:
  stfb_dataspec: "B:TPC/RAWDATA"
control:
   mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: "from_Dispatcher_to_QC-TASK-RUNNER-dataDistribution"
    type: "push"
    rateLogging: "60"
command:
  shell: true
  value: >-
    eval `aliswmod load QualityControl Control-OCCPlugin` &&
    o2-dpl-raw-proxy -b --dataspec {{stfb_dataspec}} | o2-qc
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "{{ monitoring_qc_url }}"
    - "--id"
    - "Dispatcher"
    - "--log-color"
    - "false"
    - "--config"
    - "json:///home/flp/datadistribution.json"
    - "--readers"
    - "1"
