name: stfb-raw-proxy
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: from_readout-proxy_to_Dispatcher
    type: push
    rateLogging: "60"
command:
  shell: true
  value: >-
    source /etc/profile.d/modules.sh &&
    MODULEPATH=/opt/alisw/el7/modulefiles module load QualityControl &&
    MODULEPATH=/opt/alisw/el7/modulefiles module load Control-OCCPlugin &&
    o2-dpl-raw-proxy -b | o2-qc --config json:///home/flp/datadistribution.json | o2-dpl-raw-proxy
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "no-op://"
    - "--id"
    - "readout-proxy"
    - "--log-color"
    - "false"
    - "--dataspec"
    - "B:TPC/RAWDATA"
    - "--readers"
    - "1"
    - "--start-value-enumeration"
    - "0"
    - "--step-value-enumeration"
    - "1"
    - "--end-value-enumeration"
    - "-1"

