name: stfbuilder-senderoutput
control:
  mode: fairmq
defaults:
  rdh_version: "6"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: buildertosender
    type: push
    rateLogging: "1"
    transport: shmem
    addressing: ipc
    sndBufSize: "1"
command:
  env: []
  shell: true
  user: flp
  value: >-
    eval `aliswmod load DataDistribution Control-OCCPlugin` &&
    StfBuilder
  arguments:
    - "--detector"
    - "TPC"
    - "--output-channel-name=buildertosender"
    - "--verbosity=veryhigh"
    - "--detector-rdh"
    - "{{ rdh_version }}"
