name: stfb-qc-task-runner-dd
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: "from_QC-TASK-RUNNER-dataDistribution_to_QC-CHECK-RUNNER-QcCheck"
    type: "push"
    rateLogging: "60"
command:
  shell: true
  value: >-
    source /etc/profile.d/modules.sh &&
    MODULEPATH=/opt/alisw/el7/modulefiles module load QualityControl &&
    MODULEPATH=/opt/alisw/el7/modulefiles module load Control-OCCPlugin &&
    o2-dpl-raw-proxy -b | o2-qc
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "no-op://"
    - "--id"
    - "QC-TASK-RUNNER-dataDistribution"
    - "--log-color"
    - "false"
    - "--config"
    - "json:///home/flp/datadistribution.json"
    - "--host"
    - "--readers"
    - "1"
    - "--period-timer-cycle"
    - "10000000"
