name: stfb-qc-dispatcher
control:
   mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: "from_Dispatcher_to_QC-TASK-RUNNER-dataDistribution"
    type: "push"
    rateLogging: "60"
command:
  shell: true
  value: >-
    source /etc/profile.d/modules.sh &&
    MODULEPATH=/opt/alisw/el7/modulefiles module load QualityControl &&
    MODULEPATH=/opt/alisw/el7/modulefiles module load Control-OCCPlugin &&
    o2-dpl-raw-proxy -b --dataspec B:TPC/RAWDATA | o2-qc
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "no-op://"
    - "--id"
    - "Dispatcher"
    - "--log-color"
    - "false"
    - "--config"
    - "json:///home/flp/datadistribution.json"
    - "--host"
    - "--readers"
    - "1"
    - "--dataspec"
    - "B:TPC/RAWDATA"
